/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "665b0e8923549ef080ece8f6b2125de90a8e9e0c"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
